eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
  ##开发环境时把自我保护机制设为false
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
#server:
#  port: 8761
